name: quami
version: 0.1.0.0
github: "lukasberglund/quami"
license: BSD3
author: "John Maar, Lukas Berglund"
maintainer: "lukas.t.berglund@gmail.com"
copyright: "2020 Maar, Berglund"

dependencies:
- base >= 4.8 && < 5
- containers
- matrix

ghc-options:
  - -Wall
  - -Werror
  - -dcore-lint
  - -fno-warn-incomplete-patterns
  - -fwarn-unused-imports
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src

executables:
  quami-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quami

tests:
  quami-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quami
      - hspec
      # - process
      - text
